### ISSUE TITLE
Alignment procedure explanation blog is offline

### ISSUE THREAD

**Issue by lfcc1** [babylonhealth/fastText_multilingual#27]
Hello,
The blog mentioned in the readme is offline. (https://www.samtalksml.net/aligning-vector-representations/) 
Would it be possible to make thet blog available again?
Thank you

**Comment by bodak** [comment]
Hi Filipe,
You can reach the blog (text) for now with the help of WayBackMachine.
https://web.archive.org/web/20201111222742/https://www.samtalksml.net/aligning-vector-representations/

I will look into sourcing and storing this within the repo.
